services:
  gandi-dyndns:
    build:
      context: .
    volumes:
      - ./crontab.txt:/etc/crontabs/root
      - ./logs:/var/log
    environment:
      GANDI_API_KEY: "<apikey>"  # Replace with your actual API key
      DOMAIN: "<example.com>"    # Replace with your actual domain
      SUBDOMAIN: "<subdomain>"   # Replace with your actual subdomain
      TTL: 300                   # Default value for TTL
      IPLOOKUP: "http://whatismyip.akamai.com/"  # Default value for IP lookup service
    command: ["crond", "-f"]
